title: Kumaresh Vijayakumar
logo: https://avatars.githubusercontent.com/u/63708215?s=400&u=ae6fd02ff9e0c3a0f9a3bad80cdcd6ab12f3591f&v=4
description:  BI Engineer | Data Analyst
theme: jekyll-theme-slate
